### ISSUE TITLE
strong tags

### ISSUE THREAD

**Issue by rimmesbe** [NinaOConnell/prj-rev-bwfs-dasmoto#3]
Span tags and strong tags are basically the same except a strong tag defaults to bold and semantically represents importance. You should not need both of those elements together. 

Also, don't use inline styling like you are doing in the span. Keep all your styling in the stylesheet. Inline styling is inefficient and very hard to overwrite.

https://github.com/NinaOConnell/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts%26Crafts/index.html#L22

**Comment by NinaOConnell** [comment]
Thanks! Could you show me an example of how I would do that to only part of a sentence in the stylesheet?

**Comment by rimmesbe** [comment]
`<p>This a paragraph text, and this text is <span class="blue">blue</span></p>`
.blue { color: blue; }

**Comment by NinaOConnell** [comment]
Thank you! This makes so much sense now -- especially with a little more studying under my belt.
